### ISSUE TITLE
error build userregsvc

### ISSUE THREAD

**Issue by fajarfathurrahman** [debianmaster/microservices-on-openshift#6]
hi i got error when try to built userregsvc,
i am using ocp 3.11.59

here is the log:
`
Using docker-registry.default.svc:5000/openshift/nodejs@sha256:9dce2f60b87b2eea351213c3d142716c0a70c894df8b3d2d4425b4933b8f6221 as the s2i builder image
---> Installing application source
---> Building your Node application from source
Current git config
url.https://github.com.insteadof=git@github.com: 
url.https://.insteadof=ssh:// 
url.https://github.com.insteadof=ssh://git@github.com 
---> Installing dependencies
[eval]:1
console.log(require('./package.json').scripts.build ? true : false)
                                             ^

TypeError: Cannot read property 'build' of undefined
    at [eval]:1:46
    at Script.runInThisContext (vm.js:122:20)
    at Object.runInThisContext (vm.js:329:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at evalScript (internal/bootstrap/node.js:589:27)
    at startup (internal/bootstrap/node.js:265:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error: build error: non-zero (13) exit code from docker-registry.default.svc:5000/openshift/nodejs@sha256:9dce2f60b87b2eea351213c3d142716c0a70c894df8b3d2d4425b4933b8f6221
`

**Comment by debianmaster** [comment]
this repo is kinda of outdated.   and no longer maintained.        you mind sending a pull request if it works for you?
